[project]
name = "pythonproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "requests",
    "utils3",
]

[tool.uv.sources]
utils3 = { git = "https://github.com/the-sal/utils3" }
